"""initial migration

Revision ID: 958bd29238a7
Revises: db2df78b7151
Create Date: 2023-04-02 07:10:44.435157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958bd29238a7'
down_revision = 'db2df78b7151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('admin_division', sa.Integer(), nullable=True))
    op.add_column('country', sa.Column('num_admin_division', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'country', 'admin_division', ['admin_division'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='foreignkey')
    op.drop_column('country', 'num_admin_division')
    op.drop_column('country', 'admin_division')
    # ### end Alembic commands ###
