"""initial migration

Revision ID: 310883ca43f2
Revises: 
Create Date: 2023-03-27 10:50:45.033675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '310883ca43f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_division')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('capital', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('gained_independence', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_of_independence', sa.DATE(), nullable=True),
    sa.Column('iso_code', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('country_code', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('utc_zone', mysql.ENUM('GMT__1', 'GMT_0', 'GMT_1', 'GMT_2', 'GMT_3', 'GMT_4'), nullable=True),
    sa.Column('admin_div', mysql.ENUM('Department', 'District', 'Commune', 'Governorate', 'Municipality', 'Parish', 'Prefecture', 'Province', 'Region', 'State', 'Sub_district'), nullable=True),
    sa.Column('num_div', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('admin_division',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('capital_seat', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('country', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_div', mysql.ENUM('Department', 'District', 'Commune', 'Governorate', 'Municipality', 'Parish', 'Prefecture', 'Province', 'Region', 'State', 'Sub_district'), nullable=True),
    sa.Column('num_div', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['country.id'], name='admin_division_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
