"""initial migration

Revision ID: dd5433bc4863
Revises: 310883ca43f2
Create Date: 2023-03-27 14:21:53.507175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd5433bc4863'
down_revision = '310883ca43f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=250), nullable=False))
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
